# Site settings
title: These Software Things
email: eesonyu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Development notes, IT process, trivia, ...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sychen.github.io" # the base hostname & protocol for your site
twitter_username: eesonyu
github_username:  sychen

# Build settings
markdown: kramdown

gems: [jekyll-paginate, jekyll-gist]

kramdown:
  input: GFM
  syntax_highlighter: rouge

